### ISSUE TITLE
[Refactor] 参数校验方式统一修改

### ISSUE THREAD

**Issue by frank-zsy** [2020NCOV/ncov-report-mini-program-server#4]
目前大量接口都有参数校验，但各自校验导致大量的冗余代码，而且获取参数方式不一致，可以完整抽象为统一的帮助函数。

请问：
Request::instance()->post('code') 和 input('post.code') 是否完全等价？如果等价可以建议统一用后者

**Comment by zhangqixun** [comment]
是等价的。

**Comment by frank-zsy** [comment]
> 是等价的。

好的，那我先把参数校验这块统一抽象一下
